/**
 * Runs the TypeScript engine over model/fixtures/sequences.json and writes the
 * expected outputs to model/fixtures/golden.json. The Swift engine's tests
 * replay the same inputs and must reproduce these numbers, so the web app and
 * the iOS app cannot silently drift apart.
 *
 *   npm run golden          # regenerate after changing the model or engine
 */
import { readFileSync, writeFileSync } from "node:fs";
import { EmotionEngine, type EmotionModel, type FrameResult, type Platform } from "../src/engine/index.ts";

const root = new URL("../../model/", import.meta.url);
const model = JSON.parse(readFileSync(new URL("emotion-model.json", root), "utf8")) as EmotionModel;

export interface SequenceFrame {
  t: number;
  m: Record<string, number> | null;
  cmd?: string;
}
export interface Sequence {
  name: string;
  platform: Platform;
  frames: SequenceFrame[];
}

const r6 = (v: number) => Math.round(v * 1e6) / 1e6;

export function goldenFrame(r: FrameResult, auIds: string[], withAUs: boolean) {
  return {
    t: r.t,
    face: r.face,
    primary: r.primary.id,
    complex: r.complex.map((c) => c.id),
    calibrated: r.calibrated,
    scores: Object.fromEntries(Object.entries(r.scores).map(([k, v]) => [k, r6(v)])),
    aus: withAUs ? Object.fromEntries(auIds.filter((k) => r.aus[k] !== undefined).map((k) => [k, r6(r.aus[k])])) : {},
    pspi: r6(r.pspi),
    events: r.events.map((e) => ("id" in e ? `${e.type}:${e.id}` : e.type)),
  };
}

export function runSequence(seq: Sequence) {
  const engine = new EmotionEngine(model, seq.platform);
  const auIds = [...engine.cm.auIds, "PERCLOS", "YAWN", "STILL"];
  return seq.frames.map((f, i) => {
    if (f.cmd?.startsWith("calibrate:")) engine.startCalibration(f.t, Number(f.cmd.split(":")[1]));
    return goldenFrame(engine.process(f.t, f.m), auIds, i % 5 === 0);
  });
}

export function makeGolden() {
  const { sequences } = JSON.parse(readFileSync(new URL("fixtures/sequences.json", root), "utf8")) as { sequences: Sequence[] };
  return {
    about: "Expected engine outputs for fixtures/sequences.json, generated by web/scripts/make-golden.ts. Do not edit by hand.",
    modelVersion: model.version,
    sequences: sequences.map((s) => ({ name: s.name, platform: s.platform, frames: runSequence(s) })),
  };
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop()!)) {
  writeFileSync(new URL("fixtures/golden.json", root), JSON.stringify(makeGolden()) + "\n");
  console.log("wrote model/fixtures/golden.json");
}
